<a href="https://colab.research.google.com/github/kthanikonda/DataWithPython/blob/main/Real_Estate_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Dataset Selection and Initial Exploration

**Dataset:** Real Estate Sales Data (2001-2022)

**Source:** https://www.kaggle.com/datasets/omniamahmoudsaeed/real-estate-sales-2001-2022

**About Dataset:** This dataset provides detailed information about property sales, including various property features and sale statistics. The data spans multiple years and includes information about towns, property types, sale amounts, assessed values, and additional remarks from assessors.

### About the Columns in the Dataset

This dataset contains information about property sales. Below is what each column represents:

1. **Serial Number -** A unique ID for each property.  
2. **List Year -** The year the property was listed for sale.  
3. **Date Recorded -** When the sale was officially recorded.  
4. **Town -** The city or town where the property is located.  
5. **Address -** The street address of the property.  
6. **Assessed Value -** The value assigned for tax purposes.  
7. **Sale Amount -** The actual price the property sold for.  
8. **Sales Ratio -** Compares the sale price to the assessed value.  
9. **Property Type -** The type of property (e.g., Residential, Commercial).  
10. **Residential Type -** If residential, the specific type (e.g., Single Family).  
11. **Non Use Code -** Codes for properties not typically used (e.g., vacant land).  
12. **Assessor Remarks -** Additional notes from the assessor.  
13. **OPM Remarks -** Notes from the Office of Property Management.  
14. **Location -** The exact geographic coordinates (latitude and longitude).

# 2. Loading the Dataset into Colab

*   To begin the analysis, we first upload the dataset to Google Colab using the `files.upload()` method provided by `google.colab`. After uploading, we read the dataset using `pandas`.
*   We display the first few rows to get an initial idea of what the data looks like using `df.head()`

In [16]:
from google.colab import files
import os

uploaded = files.upload()

Saving Real_Estate_Sales_2001-2022_GL.csv to Real_Estate_Sales_2001-2022_GL (1).csv

In [17]:
import pandas as pd

df = pd.read_csv("Real_Estate_Sales_2001-2022_GL.csv")

df.head()

<ipython-input-17-50b421269604>:3: DtypeWarning: Columns (8,9,10,11,12) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("Real_Estate_Sales_2001-2022_GL.csv")

,Serial Number,List Year,Date Recorded,Town,Address,Assessed Value,Sale Amount,Sales Ratio,Property Type,Residential Type,Non Use Code,Assessor Remarks,OPM remarks,Location
0,2020177,2020,04/14/2021,Ansonia,323 BEAVER ST,133000.0,248400.0,0.5354,Residential,Single Family,NaN,NaN,NaN,POINT (-73.06822 41.35014)
1,2020225,2020,05/26/2021,Ansonia,152 JACKSON ST,110500.0,239900.0,0.4606,Residential,Three Family,NaN,NaN,NaN,NaN
2,2020348,2020,09/13/2021,Ansonia,230 WAKELEE AVE,150500.0,325000.0,0.4630,Commercial,NaN,NaN,NaN,NaN,NaN
3,2020090,2020,12/14/2020,Ansonia,57 PLATT ST,127400.0,202500.0,0.6291,Residential,Two Family,NaN,NaN,NaN,NaN
4,210288,2021,06/20/2022,Avon,12 BYRON DRIVE,179990.0,362500.0,0.4965,Residential,Condo,NaN,NaN,NaN,POINT (-72.879115982 41.773452988)

# 3. Data Import and Cleaning

In this section, We examine the dataset for missing values, inconsistent data, and incorrect data types. We also perform appropriate cleaning steps to ensure the dataset is ready for analysis.

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1097629 entries, 0 to 1097628
Data columns (total 14 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   Serial Number     1097629 non-null  int64
 1   List Year         1097629 non-null  int64
 2   Date Recorded     1097627 non-null  object
 3   Town              1097629 non-null  object
 4   Address           1097578 non-null  object
 5   Assessed Value    1097629 non-null  float64
 6   Sale Amount       1097629 non-null  float64
 7   Sales Ratio       1097629 non-null  float64
 8   Property Type     715183 non-null   object
 9   Residential Type  699240 non-null   object
 10  Non Use Code      313451 non-null   object
 11  Assessor Remarks  171228 non-null   object
 12  OPM remarks       13031 non-null    object
 13  Location          298111 non-null   object
dtypes: float64(3), int64(2), object(9)
memory usage: 117.2+ MB

In [19]:
df.describe()

       Serial Number     List Year  Assessed Value   Sale Amount   Sales Ratio
count   1.097629e+06  1.097629e+06    1.097629e+06  1.097629e+06  1.097629e+06
mean    5.370357e+05  2.011218e+03    2.818016e+05  4.053146e+05  9.603926e+00
std     7.526074e+06  6.773485e+00    1.657890e+06  5.143492e+06  1.801664e+03
min     0.000000e+00  2.001000e+03    0.000000e+00  0.000000e+00  0.000000e+00
25%     3.071300e+04  2.005000e+03    8.909000e+04  1.450000e+05  4.778667e-01
50%     8.070600e+04  2.011000e+03    1.405800e+05  2.330000e+05  6.105663e-01
75%     1.703410e+05  2.018000e+03    2.282700e+05  3.750000e+05  7.707200e-01
max     2.000500e+09  2.022000e+03    8.815100e+08  5.000000e+09  1.226420e+06

In [20]:
df.isnull().sum()

Serial Number             0
List Year                 0
Date Recorded             2
Town                      0
Address                  51
Assessed Value            0
Sale Amount               0
Sales Ratio               0
Property Type        382446
Residential Type     398389
Non Use Code         784178
Assessor Remarks     926401
OPM remarks         1084598
Location             799518
dtype: int64

In [21]:
# See % of missing values
missing_percent = (df.isnull().sum() / len(df)) * 100
missing_percent.sort_values(ascending=False)

OPM remarks         98.812805
Assessor Remarks    84.400194
Location            72.840459
Non Use Code        71.442901
Residential Type    36.295415
Property Type       34.842921
Address              0.004646
Date Recorded        0.000182
Serial Number        0.000000
List Year            0.000000
Assessed Value       0.000000
Town                 0.000000
Sale Amount          0.000000
Sales Ratio          0.000000
dtype: float64

In [22]:
# Step 1: Copy the original DataFrame to preserve raw data
cleaned_df = df.copy()
print(" Original DataFrame copied to 'cleaned_df'.")

# Step 2: Drop columns with too many missing values
columns_to_drop = ['Non Use Code', 'Assessor Remarks', 'OPM remarks']
cleaned_df.drop(columns=[col for col in columns_to_drop if col in cleaned_df.columns], inplace=True)
print(f"Dropped columns: {columns_to_drop}")

# Step 3: Fill missing values in useful categorical columns
cleaned_df['Residential Type'] = cleaned_df['Residential Type'].fillna('Unknown')
cleaned_df['Property Type'] = cleaned_df['Property Type'].fillna('Unknown')
cleaned_df['Address'] = cleaned_df['Address'].fillna('Unknown')
print(" Filled missing values in 'Residential Type', 'Property Type', and 'Address'.")

# Step 4: Convert 'Date Recorded' to datetime format
cleaned_df['Date Recorded'] = pd.to_datetime(cleaned_df['Date Recorded'], errors='coerce')
print("Converted 'Date Recorded' to datetime format.")

# Step 5: Extract coordinates from 'Location' column
cleaned_df['Longitude'] = cleaned_df['Location'].str.extract(r'POINT \((-?\d+\.\d+)')
cleaned_df['Latitude'] = cleaned_df['Location'].str.extract(r'POINT \(-?\d+\.\d+ (\d+\.\d+)')

# Convert extracted coordinates to numeric (float)
cleaned_df['Longitude'] = pd.to_numeric(cleaned_df['Longitude'], errors='coerce')
cleaned_df['Latitude'] = pd.to_numeric(cleaned_df['Latitude'], errors='coerce')
print(" Extracted and converted 'Longitude' and 'Latitude' from 'Location' column.")

# Step 6: Show result of cleaning
print("\n Cleaned DataFrame Overview:")
print(cleaned_df.info())
print("\n First few rows of cleaned data:")
print(cleaned_df.head())

✅ Original DataFrame copied to 'cleaned_df'.
✅ Dropped columns: ['Non Use Code', 'Assessor Remarks', 'OPM remarks']
✅ Filled missing values in 'Residential Type', 'Property Type', and 'Address'.
✅ Converted 'Date Recorded' to datetime format.
✅ Extracted and converted 'Longitude' and 'Latitude' from 'Location' column.

📊 Cleaned DataFrame Overview:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1097629 entries, 0 to 1097628
Data columns (total 13 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   Serial Number     1097629 non-null  int64
 1   List Year         1097629 non-null  int64
 2   Date Recorded     1097627 non-null  datetime64[ns]
 3   Town              1097629 non-null  object
 4   Address           1097629 non-null  object
 5   Assessed Value    1097629 non-null  float64
 6   Sale Amount       1097629 non-null  float64
 7   Sales Ratio       1097629 non-null  float64
 8   Property Type     1097629 non-null  object
 9   Residential Type  1097629 non-null  object
 10  Location          298111 non-null   object
 11  Longitude         298110 non-null   float64
 12  Latitude          298110 non-null   float64
dtypes: datetime64[ns](1), float64(5), int64(2), object(5)
memory usage: 108.9+ MB
None

🧪 First few rows of cleaned data:
   Serial Number  List Year Date Recorded     Town          Address  \
0        2020177       2020    2021-04-14  Ansonia    323 BEAVER ST
1        2020225       2020    2021-05-26  Ansonia   152 JACKSON ST
2        2020348       2020    2021-09-13  Ansonia  230 WAKELEE AVE
3        2020090       2020    2020-12-14  Ansonia      57 PLATT ST
4         210288       2021    2022-06-20     Avon   12 BYRON DRIVE

   Assessed Value  Sale Amount  Sales Ratio Property Type Residential Type  \
0        133000.0     248400.0       0.5354   Residential    Single Family
1        110500.0     239900.0       0.4606   Residential     Three Family
2        150500.0     325000.0       0.4630    Commercial          Unknown
3        127400.0     202500.0       0.6291   Residential       Two Family
4        179990.0     362500.0       0.4965   Residential            Condo

                             Location  Longitude   Latitude
0          POINT (-73.06822 41.35014) -73.068220  41.350140
1                                 NaN        NaN        NaN
2                                 NaN        NaN        NaN
3                                 NaN        NaN        NaN
4  POINT (-72.879115982 41.773452988) -72.879116  41.773453

In [23]:
cleaned_df.head()

,Serial Number,List Year,Date Recorded,Town,Address,Assessed Value,Sale Amount,Sales Ratio,Property Type,Residential Type,Location,Longitude,Latitude
0,2020177,2020,2021-04-14,Ansonia,323 BEAVER ST,133000.0,248400.0,0.5354,Residential,Single Family,POINT (-73.06822 41.35014),-73.068220,41.350140
1,2020225,2020,2021-05-26,Ansonia,152 JACKSON ST,110500.0,239900.0,0.4606,Residential,Three Family,NaN,NaN,NaN
2,2020348,2020,2021-09-13,Ansonia,230 WAKELEE AVE,150500.0,325000.0,0.4630,Commercial,Unknown,NaN,NaN,NaN
3,2020090,2020,2020-12-14,Ansonia,57 PLATT ST,127400.0,202500.0,0.6291,Residential,Two Family,NaN,NaN,NaN
4,210288,2021,2022-06-20,Avon,12 BYRON DRIVE,179990.0,362500.0,0.4965,Residential,Condo,POINT (-72.879115982 41.773452988),-72.879116,41.773453

In [24]:
num_full_duplicates = cleaned_df.duplicated().sum()
print(f"Number of fully duplicated rows: {num_full_duplicates}")

Number of fully duplicated rows: 0

In [25]:
cleaned_df.isnull().sum()

Serial Number            0
List Year                0
Date Recorded            2
Town                     0
Address                  0
Assessed Value           0
Sale Amount              0
Sales Ratio              0
Property Type            0
Residential Type         0
Location            799518
Longitude           799519
Latitude            799519
dtype: int64

In [26]:
cleaned_df.describe()

,Serial Number,List Year,Date Recorded,Assessed Value,Sale Amount,Sales Ratio,Longitude,Latitude
count,1.097629e+06,1.097629e+06,1097627,1.097629e+06,1.097629e+06,1.097629e+06,298110.000000,298110.000000
mean,5.370357e+05,2.011218e+03,2012-06-28 08:23:23.755556864,2.818016e+05,4.053146e+05,9.603926e+00,-72.876112,41.497602
min,0.000000e+00,2.001000e+03,1999-04-05 00:00:00,0.000000e+00,0.000000e+00,0.000000e+00,-121.230910,34.345810
25%,3.071300e+04,2.005000e+03,2005-11-04 00:00:00,8.909000e+04,1.450000e+05,4.778667e-01,-73.192288,41.287632
50%,8.070600e+04,2.011000e+03,2012-08-13 00:00:00,1.405800e+05,2.330000e+05,6.105663e-01,-72.901170,41.502569
75%,1.703410e+05,2.018000e+03,2018-10-16 00:00:00,2.282700e+05,3.750000e+05,7.707200e-01,-72.629131,41.715729
max,2.000500e+09,2.022000e+03,2023-09-29 00:00:00,8.815100e+08,5.000000e+09,1.226420e+06,-71.187550,44.934590
std,7.526074e+06,6.773485e+00,NaN,1.657890e+06,5.143492e+06,1.801664e+03,0.444885,0.259391

In [27]:
cleaned_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1097629 entries, 0 to 1097628
Data columns (total 13 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   Serial Number     1097629 non-null  int64
 1   List Year         1097629 non-null  int64
 2   Date Recorded     1097627 non-null  datetime64[ns]
 3   Town              1097629 non-null  object
 4   Address           1097629 non-null  object
 5   Assessed Value    1097629 non-null  float64
 6   Sale Amount       1097629 non-null  float64
 7   Sales Ratio       1097629 non-null  float64
 8   Property Type     1097629 non-null  object
 9   Residential Type  1097629 non-null  object
 10  Location          298111 non-null   object
 11  Longitude         298110 non-null   float64
 12  Latitude          298110 non-null   float64
dtypes: datetime64[ns](1), float64(5), int64(2), object(5)
memory usage: 108.9+ MB

In [29]:
zero_sales_count = (cleaned_df['Sale Amount'] == 0).sum()
print(f"❗ Rows with Sale Amount = 0: {zero_sales_count}")

❗ Rows with Sale Amount = 0: 1810

In [30]:
cleaned_df['Valid Sale'] = cleaned_df['Sale Amount'] > 0

In [31]:
print(" Count of valid and invalid sales:")
print(cleaned_df['Valid Sale'].value_counts())

 Count of valid and invalid sales:
Valid Sale
True     1095819
False       1810
Name: count, dtype: int64

In [32]:
cleaned_df[['Sale Amount', 'Valid Sale']].head(10)

   Sale Amount  Valid Sale
0     248400.0        True
1     239900.0        True
2     325000.0        True
3     202500.0        True
4     362500.0        True
5     400000.0        True
6     775000.0        True
7     415000.0        True
8     243000.0        True
9     100000.0        True

In [33]:
print(f" Total records in cleaned_df: {len(cleaned_df)}")

 Total records in cleaned_df: 1097629

In [34]:
cleaned_df['Valid Assessed'] = cleaned_df['Assessed Value'] > 0
print(cleaned_df['Valid Assessed'].value_counts())

Valid Assessed
True     1090440
False       7189
Name: count, dtype: int64

In [35]:
for col in ['Town', 'Property Type', 'Residential Type']:
    cleaned_df[col] = cleaned_df[col].str.strip().str.title()

In [36]:
cleaned_df.head()

,Serial Number,List Year,Date Recorded,Town,Address,Assessed Value,Sale Amount,Sales Ratio,Property Type,Residential Type,Location,Longitude,Latitude,Valid Sale,Valid Assessed
0,2020177,2020,2021-04-14,Ansonia,323 BEAVER ST,133000.0,248400.0,0.5354,Residential,Single Family,POINT (-73.06822 41.35014),-73.068220,41.350140,True,True
1,2020225,2020,2021-05-26,Ansonia,152 JACKSON ST,110500.0,239900.0,0.4606,Residential,Three Family,NaN,NaN,NaN,True,True
2,2020348,2020,2021-09-13,Ansonia,230 WAKELEE AVE,150500.0,325000.0,0.4630,Commercial,Unknown,NaN,NaN,NaN,True,True
3,2020090,2020,2020-12-14,Ansonia,57 PLATT ST,127400.0,202500.0,0.6291,Residential,Two Family,NaN,NaN,NaN,True,True
4,210288,2021,2022-06-20,Avon,12 BYRON DRIVE,179990.0,362500.0,0.4965,Residential,Condo,POINT (-72.879115982 41.773452988),-72.879116,41.773453,True,True